version: '3.7'

services:
  rs0_node3:
    image: mongo:4.2
    command: mongod --config /data/configdb/mongod.conf
    networks:
      mgnet:
        ipv4_address: 20.0.2.4
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/services/rs0/node3/:/data/
      - /data/mongo/standalone/services/rs0/configs:/data/configdb/
