version: '3.7'

services:
  rs0_node1:
    image: mongo:4.2
    command: mongod --config /data/configdb/mongod.conf
    networks:
      mgnet:
        ipv4_address: 20.0.2.2
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/services/rs0/node1/:/data/
      - /data/mongo/standalone/services/rs0/node1/db:/data/db
      - /data/mongo/standalone/services/rs0/configs:/data/configdb/