version: '3.7'

networks:
  mgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/16

services:
  init_cluster:
    build: 
      context: alpine/.
    image: jenner/alpine:mongodb.4.0.5-r0
    command: sh /data/scripts/mongo-cluster-operations.sh
    networks:
      - mgnet
    dns:
      - 223.5.5.5
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/scripts:/data/scripts
    depends_on:
      - rs0_node1
      - rs0_node2
      - rs0_node3
      - rs1_node1
      - rs1_node2
      - rs1_node3
      - cfg1
      - cfg2
      - cfg3
      - mongos
    links:
      - rs0_node1
      - rs1_node1
      - cfg1
