version: '3.7'

networks:
  mgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/16

services:
  init_cluster:
    build: 
      context: alpine/.
    image: alpine:mongo
    command: bash /data/scripts/mongo-cluster-operations.sh
    networks: 
      - mgnet
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/scripts:/data/scripts
    depends_on:
      - rs0_node1
      - rs0_node2
      - rs0_node3
      - rs1_node1
      - rs1_node2
      - rs1_node3
      - cfg1
      - cfg2
      - cfg3
      - mongos
    links:
      - rs0_node1
      - rs1_node1
      - cfg1
