version: '3.7'

services:
  cfg2:
    image: mongo:4.0
    command: mongod --config /data/configdb/mongod.conf
    networks:
      mgnet:
        ipv4_address: 20.0.0.3
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/services/cfg-server/node2/:/data/
      - /data/mongo/standalone/services/cfg-server/node2/db:/data/db
      - /data/mongo/standalone/services/cfg-server/configs:/data/configdb
  