version: '3.7'

services:
  cfg1:
    image: mongo:4.2
    command: mongod --config /data/configdb/mongod.conf
    networks:
      mgnet:
        ipv4_address: 20.0.0.2
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/cfg-server/node1:/data
      - /data/mongo/standalone/cfg-server/configs:/data/configdb
      - /data/mongo/standalone/certs:/data/certs
