version: '3.7'

services:
  cfg3:
    image: mongo:4.2
    command: mongod --config /data/configdb/mongod.conf
    networks:
      mgnet:
        ipv4_address: 20.0.0.4
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/standalone/services/cfg-server/node3:/data
      - /data/mongo/standalone/services/cfg-server/configs:/data/configdb
  